function Hd = HighPassFilter(Freq)
%HIGHPASSFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 30-Jan-2015 09:19:47
%

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = Freq;  % Sampling Frequency

N     = 10;   % Order
Fstop = 300;  % Stopband Frequency
Fpass = 400;  % Passband Frequency
Wstop = 1;    % Stopband Weight
Wpass = 1;    % Passband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop Fpass Fs/2]/(Fs/2), [0 0 1 1], [Wstop Wpass], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
